{"version":1,"ops":[{"type":1,"author":{"id":"ba1625a6608e712ded2a67f4a8029f0ddc5b0159"},"timestamp":1358448795,"metadata":{"github-id":"MDU6SXNzdWUxMDA3MDEwMA==","github-url":"https://github.com/perl11/p2/issues/3","origin":"github"},"title":"Unstable exception handling","message":"darwin:\n\n```\ntest/flow/except.pn: expected \u003cTRY 1\nTRY ERROR!\nRESUMING\nSUCCESS\nTRY 2\nSUCCESS\nnil\u003e, but got \u003cTRY 1\nTRY 2\nSUCCESS\nnil\u003e\n```","files":null}]}